### PR TITLE
✨ Automatically chime in on ticket mentions

### PR DESCRIPTION
**Pull request by xurizaemon**
Have been using this in a fork for some time, realised it doesn't seem to be PR'd

### CODE REVIEW

**Comment by stephenyeargin** [comment]
This is a great contribution that I think folks will find helpful! See my note above about something to consider, but not necessarily a blocker as long as we communicate the change.

**Comment by xurizaemon** [comment]
OK, how does this look?

`HUBOT_REDMINE_MENTION_REGEX` defaults to `/#(\d+)/` and can be overridden with eg `/RM#(\d+)/`, `/(?:AB|CD)#(\d+)/` etc to suit, capturing the issue id in `msg.match[1]`. Default trigger could be `RM#123` but I think `#123` is more discoverable?

**Comment by xurizaemon** [comment]
I hear you on the URL suggestion but I would never bother typing a full URL into a channel, while I find being able to type #31 in channel as convenient as it gets (and I could live with GH#31 or RM#31 which is how it would work at our office, to avoid conflicts with another ticket system).

**Comment by stephenyeargin** [comment]
I think this will work fine. If a user wants to disable the feature entirely, they could put a nonsense string in the regex.

**Pull request merged**
